[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 4321
